name: 'Containerized Action'
description: 'A custom action packaged as a Docker container'
inputs:
  name:
    description: 'The name to greet'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'