name: 02. Complex Workflows

on:
  push:

jobs:
  parallel-job-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run parallel job 1
        run: echo "Running parallel job 1"

  parallel-job-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run parallel job 2
        run: echo "Running parallel job 2"

  sequential-job:
    runs-on: ubuntu-latest
    needs: [parallel-job-1, parallel-job-2]
    steps:
      - uses: actions/checkout@v4
      - name: Run sequential job
        run: echo "Running sequential job"

  matrix-build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: sample-app
    strategy:
      fail-fast: false
      matrix:
        node-version: [12, 14, 16]
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test

  reusable-workflow:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      some-input: some-value
