name: Custom Actions

on:
  push:
    branches:
      - main

jobs:
  custom-js-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run custom JavaScript action
        uses: ./.github/actions/custom-js-action

  containerized-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run containerized action
        uses: ./.github/actions/containerized-action

  composite-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run composite action
        uses: ./.github/actions/composite-action
